### ISSUE TITLE
readme not clear on purpose or contribution guidelines

### ISSUE THREAD

**Issue by mprorock** [w3c-ccg/vc-api#101]
The readme attached to this repo needs some enhancement to make it easier for new developers to approach the API or those wishing to implement the API in a conformant manner.

There are also no contribution guidelines, etc.

Happy to jump in and take a stab at getting some better docs pulled together on this.

**Comment by OR13** [comment]
Agreed, we had previously resolved to follow an api style guide.

https://restfulapi.net/

I suggest we add some guidance related to that to the top level readme, and explictly address the `controller` vs `collection` style endpoints.

**Comment by mprorock** [comment]
editors: @peacekeeper @msporny @mavarley @OR13 @mkhraisha 
can we add the tag: `plugfest-march-2021` to this issue

**Comment by msporny** [comment]
We discussed this in 2022-01-18, @mprorock provided an update where contribution guidelines were documented via PRs that were merged. Also discussed in issue #97 ... group decided to close this issue as a result.
