### ISSUE TITLE
Enable HTTP requests to specify optional verification checks

### ISSUE THREAD

**Issue by bumblefudge** [w3c-ccg/vc-api#104]
Discussing the API with @alexyenkalov and @therecanbeonlyone1969 , we considered a broader solution to the topic discussed in issue #90 . Perhaps revocation should be only one of the optional checks that verifiers could communicate over the API?

We are proposing (**NOT FOR MARCH**, but to discuss after the plug-a-thon) to enable JSON Schema validation by default for all the optional properties mentioned in the VC data model specification if present: not just credentialStatus, but also evidence, etc.

Enable additional, optional checks via `checks` array in HTTP request body options:
- proof (only signature check)
- status (revocation check, i.e. revocation-list-2020)
- dates (issuance < now < expiration)
- evidence (check semantics of dereferenced evidence URI against registered JSON-LD schema: per evidence type)

**Comment by peacekeeper** [comment]
On the [05 Oct 2021 VC API Work Item call](https://w3c-ccg.github.io/meetings/2021-10-05-vchttpapi/) people felt that variability of checks is bad (see https://github.com/w3c-ccg/vc-api/issues/74#issuecomment-935880559, https://github.com/w3c-ccg/vc-api/issues/59#issuecomment-935865183, https://github.com/w3c-ccg/vc-api/issues/62#issuecomment-935852686)

**Comment by msporny** [comment]
The group discussed this on a 2021 call and the 2022-01-18 telecon. @peacekeeper provided a report out on the groups decision to reduce optionality, @mprorock provided feedback on our ability to now verify the API via OAS and JSON Schema. The group decided that we have addressed this issue. Closing.
