### ISSUE TITLE
with the latest test additions it is not clear how to add a test

### ISSUE THREAD

**Issue by mprorock** [w3c-ccg/vc-api#105]
with the great work done in pr #94 it is not clear to me how a new company would add themselves to the test suite? happy to add documentation around this, but if i do it just by stumbling through the code I may do something wrong.

What is the best way I can go about getting this documented up?

**Comment by mprorock** [comment]
editors: @peacekeeper @msporny @mavarley @OR13 @mkhraisha
can we add the tag: `plugfest-march-2021` to this issue

**Comment by mprorock** [comment]
bump editors: @peacekeeper @msporny @mavarley @OR13 @mkhraisha
can we add the tag: plugfest-march-2021 to this issue?

Surprised at the crickets on this - seems like making sure we can onboard partners and verify code for interop across the board is a good thing - should i just add a PR on some docs for this and hope they are right?  just trying to figure out how to contribute appropriately here and get this API and related tests working in a way that we can present to our customers

**Comment by bumblefudge** [comment]
seems a good addition to documentation, not sure how I can help but at the very least tag me and I can be a second TallTed clarifying and expanding on the first draft?

**Comment by mprorock** [comment]
@bumblefudge sounds good - i am getting something started and will notify you when i have a draft PR ready

**Comment by msporny** [comment]
We discussed this on the 2022-01-18 call, @mprorock noted that this issue has been long since resolved via PRs. Closing.
