### ISSUE TITLE
Add CourseCompletion example to test vectors

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/vc-api#106]
```json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://www.w3.org/2018/credentials/examples/v1",
    "https://w3c-ccg.github.io/lds-jws2020/contexts/lds-jws2020-v1.json",
    "https://w3id.org/dcc/v1"
  ],
  "id": "1fe91f0f-4c64-48c8-bfc8-7132f75776fe/",
  "type": [
    "VerifiableCredential",
    "LearningCredential"
  ],
  "issuer": {
    "type": "Issuer",
    "id": "did:web:digitalcredentials.github.io",
    "name": "Sample Issuer",
    "url": "https://digitalcredentials.github.io/samples/"
  },
  "issuanceDate": "2020-01-19T18:22:34.772810+00:00",
  "credentialSubject": {
    "type": "Person",
    "id": "did:example:456",
    "name": "Percival Devonte",
    "hasCredential": {
      "type": [
        "EducationalOccupationalCredential",
        "CourseCompletionCredential"
      ],
      "name": "Flow Cytometry Quality Control and Quality Assurance",
      "description": "Awarded on completion of Flow Cytometry Quality Control and Quality Assurance Course",
      "awardedOnCompletionOf": {
        "type": [
          "Course"
        ],
        "courseCode": "course-v1:flowCytometryQcIntro",
        "name": "Introduction to Quality Control and Quality Assurance in Flow Cytometry",
        "description": "Discusses regulatory requirements for flow cytometry; explains how sample preparation and instrument function are related to quality control and quality assurance",
        "numberOfCredits": {
          "value": "2.4"
        },
        "hasCourseInstance": {
          "type": "CourseInstance",
          "startDate": "2020-09-01T00:00:00.000Z",
          "endDate": "2020-10-07T00:00:00.000Z"
        }
      }
    }
  }
}
```

**Comment by OR13** [comment]
@kimdhamilton hmm feels like course completion should have a type “CourseCompletion” instead of “LearningCredential”

**Comment by kimdhamilton** [comment]
I'm interested to discuss that. 

I interpret the outermost level of a VC as nothing more than "issuer made claim(s) about subject". At that level there may be a few expected properties (for interoperability) that we'd want, e.g. those expected of wallets/systems consuming VCs the VC-EDU task force is recommending.

The idea is to push the differing type information down to the level that needs it. On the outermost level, we can define `LearningCredential` that might have certain expected properties (beyond those that come along with a basic VC) that a broad range of "Learning Credential"-aware wallets or consumers know. (This specific example doesn't show use of that, but suppose we had a few "standard" VC-EDU properties on the outermost level)

![VC-ED model](https://user-images.githubusercontent.com/3945683/107444812-24618c00-6af0-11eb-9a49-3ebd0780cd1b.png)

Then within `credentialSubject` we define the relationship between the subject and different "concepts" in the diagram above, which will have their own types. This seems more streamlined, and less duplicative, say if we want to write all of this in json schema.

**Comment by msporny** [comment]
This repository is no longer used for the test suite. Moving to https://github.com/w3c/vc-test-suite
