### ISSUE TITLE
Add Program Completion example credential

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/vc-api#107]
```
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://www.w3.org/2018/credentials/examples/v1",
    "https://w3c-ccg.github.io/lds-jws2020/contexts/lds-jws2020-v1.json",
    "https://w3id.org/dcc/v1"
  ],
  "id": "96d91bcf-40cd-4058-ad1c-f199c5d08b3b",
  "type": [
    "VerifiableCredential",
    "LearningCredential"
  ],
  "issuer": {
    "type": "Issuer",
    "id": "did:web:digitalcredentials.github.io",
    "name": "Sample Issuer",
    "url": "https://digitalcredentials.github.io/samples/"
  },
  "issuanceDate": "2021-01-19T18:22:34.772810+00:00",
  "credentialSubject": {
    "type": "Person",
    "id": "did:example:456",
    "name": "Percival Devonte",
    "hasCredential": {
      "type": [
        "EducationalOccupationalCredential",
        "ProgramCompletionCredential"
      ],
      "name": "Basics of Flow Cytometry Completion Certificate",
      "description": "Awarded on completion of the Basic Concepts and Clinical Applications of Flow Cytometry Certificate Program",
      "awardedOnCompletionOf": {
        "type": "EducationalOccupationalProgram",
        "identifier": "program-v1:FlowCytometry",
        "name": "Basic Concepts and Clinical Applications of Flow Cytometry",
        "description": "This is a basic to intermediate-level online certificate program, which will provide participants with essential knowledge about the use of flow cytometry as a diagnostic tool for the identification of various human diseases. It is intended for laboratory professionals (medical technologists, laboratory managers, laboratory directors), pathologists, core flow cytometry operators, and research scientists who are using flow cytometry in their research. Participants will learn the basics of flow cytometry and how it can be used for diagnosis.",
        "numberOfCredits": {
          "value": "12.0"
        },
        "startDate": "2020-07-01T00:00:00.000Z",
        "endDate": "2020-12-14T00:00:00.000Z"
      }
    }
  }
}
```

**Comment by OR13** [comment]
Reminder to review the context definition and the magic:

```
"awardedOnCompletionOf": { "@reverse": "schema:educationalCredentialAwarded" },
```

@tplooker ever seen this ^ ?

**Comment by mprorock** [comment]
looks like clever use of [reverse](https://json-ld.org/spec/latest/json-ld/#reverse-properties) on the json-ld spec

**Comment by kimdhamilton** [comment]
This was at least a near-to-mid-term (interim) solution that came up in the VC-ED task force, from Phil Barker, who developed the relevant "EOCred" types for schema.org, e.g https://schema.org/EducationalOccupationalProgram, and https://schema.org/EducationalOccupationalCredential. He mentioned this is sometimes used as a stopgap when the schema.org arrows don't go the way you want. 

See diagram:

<img width="836" alt="Screen Shot 2021-02-09 at 4 15 33 PM" src="https://user-images.githubusercontent.com/3945683/107445831-11e85200-6af2-11eb-90e8-fd1b5ba64bc8.png">

and we defined `awardedOnCompletionOf` in our [json-ld context](https://github.com/digitalcredentials/dcc/blob/main/v1/dcc-context-v1.json)

The hedging in my language comes only from the fact that, eventually, we may end up proposing new properties to schema.org to make the arrows go the way we want, but this felt more future proof than making up a property name --  which would have a strong chance of being tweaked before actually being adopted to schema.org.

**Comment by msporny** [comment]
@OR13, we discussed this on the 2022-01-08 call. @dmitrizagidulin and @kayaelle suggested we move this over to one of the VC EDU repos. Are you ok with that?

**Comment by msporny** [comment]
No movement in a year, no target repo, closing. Re-open if you disagree.
