### ISSUE TITLE
Define type of Oauth2 bearer token for plugfest 2021?

### ISSUE THREAD

**Issue by Therecanbeonlyone1969** [w3c-ccg/vc-api#113]
@tplooker @mprorock @OR13 ... should we define what type of bearer token should be issued e.g. JWT or should we leave that up to each Oauth server and just not care? No particular opinion on this. Just asking.

**Comment by mprorock** [comment]
we are currently using JWT, but I am open on this.

**Comment by OR13** [comment]
I would prefer we provide some examples for popular OAuth providers like Auth0.

**Comment by tplooker** [comment]
Same r.e JWT, what other options were you considering @Therecanbeonlyone1969?

**Comment by Therecanbeonlyone1969** [comment]
@tplooker the rfc is non-specific on the token type ... I do not really care. I just want to take a temperature of what people's sentiments are on this. With a JWT you can define scope in one go.

**Comment by msporny** [comment]
Plugfest 2021 has long since passed. This is not where we do tests anymore. The new test suites have options for OAuth2 bearer tokens. The spec now speaks to allowed OAuth2 bearer token formats.
