### ISSUE TITLE
CD for test reports

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/vc-api#121]
On every merge, the CI should rebuild the report and push it to github-pages branch... then we should git ignore the test results locally so that PRs don't contain dist / built assets... and are easier to review.

**Comment by OR13** [comment]
We need the same thing here: https://github.com/w3c-ccg/traceability-vocab/issues/74

**Comment by OR13** [comment]
Here is an example of how to do this, PRs welcome: https://github.com/w3c-ccg/traceability-vocab/issues/74#issuecomment-782793430

**Comment by msporny** [comment]
Tests aren't done here anymore, but are in other repositories. Closing.
