### ISSUE TITLE
Proposal: The WG needs to agree to an interoperability profile that covers the suites 

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/vc-api#130]
- Ed25519VerificationKey2018, Ed25519Signature2018
- JsonWebKey2020 (P-384), JsonWebSignature2020 (ES384)
- Bls12381G1Key2020, Bls12381G2Key2020, BbsBlsSignature2020, BbsBlsSignatureProof2020

**Comment by msporny** [comment]
I'm just going to say this out loud:

1. DB is supportive of this profile.
2. Bls is for selective disclosure, and is a fundamentally different cryptosuite -- Ed25519 for primary, and *384 for secondary is good. I will note that we don't have a secondary if a flaw is found in Bls.

**Comment by OR13** [comment]
@tplooker is there another pairing friendly curve that we might use as a backup for bls12381 ?

**Comment by tplooker** [comment]
Yeap @OR13 [BN Curves](https://tools.ietf.org/html/draft-irtf-cfrg-pairing-friendly-curves-05#section-4.2.2) used by EPID, we elected not to use this curve as it is slower and less secure than BLS12-381.

**Comment by tplooker** [comment]
So to answer your question @msporny we could have BnBbsSignature2021 that would be functionally equivalent.

**Comment by msporny** [comment]
> Yeap @OR13 [BN Curves](https://tools.ietf.org/html/draft-irtf-cfrg-pairing-friendly-curves-05#section-4.2.2) used by EPID, we elected not to use this curve as it is slower and less secure than BLS12-381.

+1 to having an alternative, no idea if BN should be the alternative. It's good to see CFRG working on this -- we may want to engage them more formally in the next couple of months, noting that we predict some sort of W3C WG that would like to have their input on a primary and backup pairing-friendly curve that wouldn't be susceptible to the same sorts of attacks.

It might also be useful to chase down Barreto, Naehrig, Lynn, and Scott to see where their current thinking is wrt. "what would you choose today for the primary and backup?"

**Comment by mavarley** [comment]
Agreed this is important, but more appropriate for https://github.com/w3c-ccg/vc-api-test-suite ?

Recommend we close this issue.
