### ISSUE TITLE
Add traceability credential to vc-http-api fixtures

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/vc-api#131]
- [ ] CMTR
- [ ] BOL
- [ ] Invoice
- [ ] Crude Product

**Comment by tplooker** [comment]
Please be sure to add both a [credential payload](https://github.com/w3c-ccg/vc-http-api/tree/master/packages/vc-http-api-test-server/__fixtures__/credentials) and [verifiable credential payload](https://github.com/w3c-ccg/vc-http-api/tree/master/packages/vc-http-api-test-server/__fixtures__/verifiableCredentials) as a stretch a [verifiable presentation payload](https://github.com/w3c-ccg/vc-http-api/tree/master/packages/vc-http-api-test-server/__fixtures__/verifiablePresentations) would be great too

**Comment by msporny** [comment]
Plugfest 2021 was over a year ago. Overcome by events. Closing.
