### ISSUE TITLE
nonce option for DeriveCredential

### ISSUE THREAD

**Issue by troyronda** [w3c-ccg/vc-api#136]
How does nonce get passed into DeriveCredential? @OR13 

Is the behavior to have the holder service generate a nonce?

If there isn't a mechanism now, suggest that we add an `options` object with a `nonce` property. Regardless, we should also understand the default behavior.

**Comment by OR13** [comment]
good question... afaik nonce is not required by derive. ping @tplooker

**Comment by troyronda** [comment]
@OR13 Looking at the JS implementation, nonce is currently generated if not provided.
https://github.com/mattrglobal/jsonld-signatures-bbs/blob/01000b4bf48932a47d7c8c889d2201f8e8085d46/src/BbsBlsSignatureProof2020.ts#L182-L185

The go implementation currently expects the nonce but we were discussing where to put the default generation (if that's the expected behaviour).

In any case, as a nonce can be provided as an option, I think it would be useful to have that option in the Holder API too.

**Comment by OR13** [comment]
personally, I would prefer if the suite was deterministic... injecting randomness for no real security benefit is bad form.

**Comment by troyronda** [comment]
> personally, I would prefer if the suite was deterministic

Agree, there should be an option to pass in nonce. We have added this option to our implementation.

**Comment by OR13** [comment]
@troyronda can you do a PR to update the spec?

**Comment by troyronda** [comment]
@OR13 #144

**Comment by msporny** [comment]
PR #144 was merged, closing.
