### ISSUE TITLE
Allow additionalProperties for options

### ISSUE THREAD

**Issue by peacekeeper** [w3c-ccg/vc-api#160]
A lot of the "options" structures set `additionalProperties: false` (e.g. see https://github.com/w3c-ccg/vc-http-api/blob/master/docs/vc-http-api.yml#L221).

I think additional properties in these "options" should be allowed to support implementation-specific extensions.

**Comment by mprorock** [comment]
Fully agree.  I think there should be a post plugfest review on vc-http-api openapi structure, and this would be an item to look at there.  There are pros and cons to allowing options parameters on a standards api to be extended, and ways to do it, without it becoming a "throw in the kitchen sink" dumping ground for vendor specific extensions

**Comment by peacekeeper** [comment]
> post plugfest

Yes :)

> vendor specific

I think it's preferable to say "implementation-specific" instead of "vendor-specific".

But thanks for your comment, and +1 to discussing pros and cons of allowing extensible options!

**Comment by mprorock** [comment]
Closing as outdated based on latest API updates and schema adjustments
