### ISSUE TITLE
__fixture__ credential naming format

### ISSUE THREAD

**Issue by mprorock** [w3c-ccg/vc-api#161]
at a later date can we adopt a naming strategy / structure to the fixtures in the test suite, perhaps a including a company id, and then an index for the example.  This would make it easier for the tests to be tied to who authored or is leveraging the credential, what number credential example is it for that author, etc.  File Name format could be something like this: `case_{COMPANY_NUMBER_OR_NAME}_{TEST_NUMBER_BY_THAT_COMPANY}_{VARIATION}.json`

This will prevent us from having to muck through a folder that potentially will have 100s of examples in it, and try and figure out by filename what is what.  That way the test number can also be paired by "type".

e.g.
```
$ ls __fixtures__/credentials
 __fixtures__/credentials/case_mesurio_01.json # ag product credential
 __fixtures__/credentials/case_mesurio_02.json # ag activity credential
$ ls __fixtures__/verifiableCredentials
 __fixtures__/verifiableCredentials/case_mesurio_01_01.json # ag product verified credential
 __fixtures__/verifiableCredentials/case_mesurio_01_02.json # ag product verified credential variation with revocation
 __fixtures__/verifiableCredentials/case_mesurio_02_01.json # ag activity verified credential 
```

we can obviously embed in the credential itself metadata to describe purpose, etc as we are doing now, and use that to build better automation around cross industry / cross company support, visualizations around test and interop results, etc.  this way there is also an easy file system as well as code way to link credential to the verified credential at a glance and add some additional meaning and understanding when debugging or perusing the repo

**Comment by mkhraisha** [comment]
I disagree with company ID but rather would have industry vectors, as this is a CCG work item i think it shouldn't be too coupled with the cohort.
I would rather something like 
```
$ ls __fixtures__/credentials
 __fixtures__/credentials/case_ag_01.json # ag product credential
 __fixtures__/credentials/case_ag_02.json # ag activity credential
 ```
which would allow for cleaner ability to associate a fixture with a vocab subentry.

**Comment by mprorock** [comment]
@mkhraisha - good call out - i linke that idea as industry verticals / sub verticals and then tie back to vocabs could be very useful

**Comment by tplooker** [comment]
Personally I'd like to keep the fixture names generalized i.e nothing but a name like case-01. We can always extract metadata from the fixture it self during test, e.g I already pull the credential.name from the fixture and render in the test.

**Comment by peacekeeper** [comment]
I also think embedding company names in filenames aren't a great idea. One of the motivations behind of the recent refactor was to generatlize the fixtures.

**Comment by msporny** [comment]
The tests are no longer a part of this repository. Closing.
