### ISSUE TITLE
did:web issuer uses publicKey instead of verificationMethod

### ISSUE THREAD

**Issue by clehner** [w3c-ccg/vc-api#175]
The `did:web` issuer of [VC case 5](https://github.com/w3c-ccg/vc-http-api/blob/b4df10d/packages/vc-http-api-test-server/__fixtures__/verifiableCredentials/case-5.json#L27) has a DID document which contains a `publicKey` property but no `verificationMethod` property.

The DID appears to resolve to this document:
https://github.com/transmute-industries/vc.transmute.world/blob/e444ce7/packages/vc-http-api/src/data/didDocument.json

`publicKey` is no longer in DID Core, as of [CR Snapshot 18 March 2021](https://www.w3.org/TR/2021/CR-did-core-20210318/), but has been renamed to `verificationMethod`. Are VC-HTTP-API implementers expected to support `publicKey` for backwards-compatibility?

**Comment by peacekeeper** [comment]
I agree this should be changed.

Note that the DID document uses an older JSON-LD context `https://w3id.org/did/v0.11`, so from a pure JSON-LD perspective, the DID document is valid. But you are right of course that the DID spec has removed `publicKey` long ago.

Funny how everybody passed the test, even though this DID document is based on a really outdated spec version :)
