### ISSUE TITLE
PROPOSAL: Move DID Resolution Interoperability testing to the did-resolution spec and work item

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/vc-api#185]
Proposal: The DID Resolution Test Suite SHALL support more than did:key (total number TBD) for did document interoperability testing.

Essentially don't use vc-http-api to test resolution when we have a perfectly good other work item for that.

**Comment by peacekeeper** [comment]
Agreed. Just created a matching issue here: https://github.com/w3c-ccg/did-resolution/issues/64

**Comment by msporny** [comment]
> proposal: The DID Resolution Test Suite SHALL support more than did:key (total number TBD) for did document interoperability testing.

We can't impose a proposal on a test suite that doesn't exist yet. :)

**Comment by mkhraisha** [comment]
This seems stale.
We should not be testing did resolultion in VC-API ( the new suites or the trace-interop suites)
