### ISSUE TITLE
Broken paths for test reports caused by changes to this repo

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/vc-api#193]
https://w3c-ccg.github.io/vc-http-api/test-suite

https://w3c-ccg.github.io/vc-http-api/test-suite/transmute

These endpoints no longer display test results, please correct this behavior by using github pages and workflows correctly

**Comment by OR13** [comment]
@msporny @peacekeeper I suspect one of you is to blame for breaking this :)

**Comment by msporny** [comment]
> @msporny I suspect one of you is to blame for breaking this :)

Yes, probably me... now that we have a spec, it's published via `main` branch... and I think those actions are running in gh-pages?

I guess we could set the publishing branch back to gh-pages, but then would have to make sure gh-pages is always rebased on top of `main`?

This is why repos are usually split into "the spec" and "the test suite" -- I suggest we do that before too long... thoughts?

**Comment by OR13** [comment]
@msporny move the spec to docs, at the root level, and let CI handle the spec and report publishing like it did before.

You can serve multiple HTML files form a single github pages directory

**Comment by OR13** [comment]
Part of our work on this test suite was to make it so that anyone could generate a report any time they wanted:

https://github.com/w3c-ccg/vc-http-api/blob/main/.github/workflows/cd.yml#L36

**Comment by msporny** [comment]
> @msporny move the spec to docs, at the root level, and let CI handle the spec and report publishing like it did before.

-1, for two reasons: 1) we shouldn't be conflating the spec with a test suite, and 2) we shouldn't have the auto-generated output of a CI process commit changes back into the main branch of a repo.

Instead, we should do one of the following:

1. Split out the test suite to it's own repo.
2. Do a build process in some "auto-generated content" branch and publish off of that.

I prefer the former as the layers are cleaner, but could agree to the latter (even though it's more complex and brittle).

**Comment by OR13** [comment]
-1 to yet another CCG repo, and -1 to breaking paths to test suite reports which we already shipped in report deliverables.

We're getting ready to add postman reports here:

https://github.com/w3c-ccg/traceability-interop/blob/main/.github/workflows/cd.yml#L27
https://github.com/w3c-ccg/traceability-interop/tree/main/docs
https://w3id.org/traceability/interoperability

We're like to be able to link to the existing reports that were working prior to the breaking changes that were merged without working group consensus.

This was all working before, and we don't need to do anything but move index.html back under `docs` where it belongs.

**Comment by bumblefudge** [comment]
+1 to w3id and stable URLs for the test reports, regardless of how they are updated upon each update to the tests.  I don't have much preference as to forks and repo etiquette/mgmt but I do think the test reports are super useful not just to client reporting but also to the DIF interop WG and other far-flung audiences of the test suites.

**Comment by Therecanbeonlyone1969** [comment]
@msporny dude, you cannot merge breaking changes without consent and heads up to other contributors that rely on working reports to 3rd parties! 

I understand that we should have two repos -> make that a work item and get some volunteers to do it. happy to pitch in.

for the time being let's keep the spec in docs folder and get a timeline together to set up two repos but revert the breaking changes.  CC @mprorock @OR13 @peacekeeper

**Comment by OR13** [comment]
When the report result behavior is fixed, I am happy to do the PR to w3id.org to make the perma urls portable...

**Comment by msporny** [comment]
> @msporny dude, you cannot merge breaking changes without consent and heads up to other contributors that rely on working reports to 3rd parties!

I didn't merge anything... I changed the Github Pages redirect based on a consensus-based resolution we made:

https://w3c-ccg.github.io/meetings/2021-05-06-vchttpapi/#resolution-1

I have changed it back to the /docs/ directory -- which breaks our spec. We now don't have a spec published on the Web at all. This is why people split these sorts of repos up... so they don't try to do double-duty... 'cause stuff like this always happens.

In addition to all of the above, you shouldn't rely on things that didn't reach consensus. We never promised that those report URLs would be around forever, until the end of time. 

So, now the repo is a different sort of broken... because it conflates three things 1) the YAML files, 2) the test report results and 3) the spec itself.

I suggest the group:

1. Splits the test suite and reporting out to a separate repo (and creates w3id.org perma-URLs to avoid this problem in the future).
2. Keeps the spec and YAML files together.

**Comment by OR13** [comment]
The documentation... in the readme:

https://github.com/w3c-ccg/vc-http-api#test-results-for-a-specific-implementation

and links that we have shipped in PDFs and blog posts, are broken...

Regardless of who's fault it is, the correct thing to do is fix this so those links work again, and then setup redirects if they need to "move to another repo"....

**Comment by msporny** [comment]
The group discussed this on 2022-04-12. Testing has been moved out into its own repository and thus this issue doesn't apply anymore. Closing.
