### ISSUE TITLE
Establish and document permanent URLs for specification and resources by version

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/vc-api#196]
We should use w3id.org and version prefixing in paths to allow external permanent links to spec and API defintion files.

we probably want things like this:

https://w3id.org/vc-http-api-> respec
https://w3id.org/vc-http-api/issuer.yml

https://w3id.org/vc-http-api/test-suite/transmute
https://w3id.org/vc-http-api/test-suite

https://w3id.org/vc-http-api/v0 -> respec
https://w3id.org/vc-http-api/v0/issuer.yml

https://w3id.org/vc-http-api/v1 -> respec
https://w3id.org/vc-http-api/v1/issuer.yml

Initially, this will work for both spec and test suite files hosted in the same repo... however we can move the test suite to a separate repo and maintain versioned links in the future if there is consensus.

Noting we probably want to have test suites for both conformance and interop.

**Comment by OR13** [comment]
Opened https://github.com/perma-id/w3id.org/pull/2211

**Comment by msporny** [comment]
The group discussed this on the 2022-04-12 telecon and there were at least four people that suggested that the specification isn't ready to be versioned at this point in time. There were no objections to not versioning the specification at this point in time. Closing.
