### ISSUE TITLE
Verifiable Presentation should be an object that supports both JWTs and JSON-LD Proofs

### ISSUE THREAD

**Issue by David-Chadwick** [w3c-ccg/vc-api#209]
The current verifier API passes a VP as an object, which is good. But the text says the object must be a VP with an LD-Proof. This excludes a JWT VP object being passed.

The OIDC protocol had the same problem, only in reverse, in that JWTs were the expected format. This has been solved in OIDC by defining an encapsulating object for the VP and inside there are types which specify whether the VP is a JWT VP or a LDproof VP.

It is receommended that the VP object that is passed to the Verify API is either the same VP object as defined in the OIDC draft, or failing that, the same concept is used, by using an encapsulating object that contains an inner type describing the type of VP

**Comment by mavarley** [comment]
covered in #208
