### ISSUE TITLE
Docs with broken links/empty sections

### ISSUE THREAD

**Issue by mkhraisha** [w3c-ccg/vc-api#215]
the docs at https://w3c-ccg.github.io/vc-http-api have many broken links and empty sections,

![image](https://user-images.githubusercontent.com/19310771/123837621-119df700-d8d9-11eb-98c5-2808f01dacd6.png)

Also need to update the Spec to outline the three different APIs ( holder/verifier/issuer).

The Readme's also need a section noting that you can access the deployed swagger by following these links: 

https://w3c-ccg.github.io/vc-http-api/verifier
https://w3c-ccg.github.io/vc-http-api/issuer
https://w3c-ccg.github.io/vc-http-api/holder

**Comment by TallTed** [comment]
s/swagger/OpenAPI (formerly Swagger)/
or similar

**Comment by mkhraisha** [comment]
sorry i dont follow, can you expand on what you're trying to say?

**Comment by TallTed** [comment]
> [@mkhraisha wrote] The Readme's also need a section noting that you can access the deployed swagger by following these links:

Swagger has been renamed OpenAPI, so the suggested section should include a note saying that _readers can access the deployed **OpenAPI (formerly Swagger)** at ..._ or similarly worded text.

**Comment by msporny** [comment]
The group discussed this on the 2023-08-01 telecon and the original broken links/sections were fixed some time ago. The group did another scan through the specification during the call and didn't find any issues with the specification related to broken links/sections. Closing.
