### ISSUE TITLE
The link to Figure 1 is broken

### ISSUE THREAD

**Issue by mwherman2000** [w3c-ccg/vc-api#217]
Check out: https://msporny.github.io/vc-http-api-spec/#a-simple-example

**Comment by regiseloi-laboidn** [comment]
`/diagrams/issue-a-vc.svg` should be replaced with `diagrams/arch-issuer-detail.svg` I believe.

**Comment by msporny** [comment]
The diagrams have been updated and fixed: https://w3c-ccg.github.io/vc-api/#architecture-overview
