### ISSUE TITLE
No authorization mechanism testable in test suite

### ISSUE THREAD

**Issue by msporny** [w3c-ccg/vc-api#234]
There is currently no authorization mechanism that can be tested by the test suite (we don't test SHOULDs or MAYs because there are regularly objections when testing optional features). 

That is, there is no minimum implementation criteria for authorization because all the authorization language in the spec are MAYs and the vendors desire a minimum bar for authorization while allowing other authorization mechanisms to also be used.

This issue can be closed once there is a mechanism in the test suite that the group agrees with that tests a minimum bar for authorization.

**Comment by msporny** [comment]
We discussed this on the 2022-03-29 telecon. Multiple implementations now have authz support and require it. The test suite needs to have support for this to access the authz-protected endpoints. We have four implementations that support OAuth2 and one implementation that supports OAuth2 and ZCAPs.

**Comment by mprorock** [comment]
see https://github.com/w3c-ccg/traceability-interop/tree/main/docs/tutorials/authentication as an example

**Comment by msporny** [comment]
We have authz mechanisms that are testable now, closing issue.
