### ISSUE TITLE
VC API should not squat on domain root URL namespace

### ISSUE THREAD

**Issue by msporny** [w3c-ccg/vc-api#244]
At present, the VC API squats on the base URL namespace

As @jricher mentioned on the call today, we should make sure that the VC API spec does not squat on the base URL namespace of the domain that hosts VC API services. Please see https://datatracker.ietf.org/doc/html/rfc7320 for more details.

**Comment by OR13** [comment]
When you configure server in OAS, you can specify the base url that is to be used... closing this as won't fix.

**Comment by msporny** [comment]
We need a statement in the specification that states clearly that the URLs in the spec are not intended to be attached to the root namespace and "can exist at any URL path" or something to that effect. Re-opening and requesting a PR to resolve this issue since I do believe we have consensus on this point.
