### ISSUE TITLE
Nit: no default file for test suite

### ISSUE THREAD

**Issue by bumblefudge** [w3c-ccg/vc-api#251]
https://w3c-ccg.github.io/vc-api-test-suite/
does not contain an index-- is there a quick way to add one or auto-generate one at each publication from [this list](https://github.com/w3c-ccg/vc-api-test-suite/blob/main/packages/vc-http-api-test-server/config/index.js)?

**Comment by OR13** [comment]
won't fix...I think the whole testing api needs to be overhauled... and I am no longer interested in maintaining test suites that don't require or check for secure configuration.
