### ISSUE TITLE
Question on the Presenting APIs

### ISSUE THREAD

**Issue by xtrycatchx** [w3c-ccg/vc-api#260]
Hi, I got an inquiry regarding the Presenting API's .. My apologies in advance if the questions doesn't makes sense..

Which `entity` should invoke the APIs defined in [https://w3c-ccg.github.io/vc-api/#presenting](https://w3c-ccg.github.io/vc-api/#presenting)? Will it be (or can it be) a wallet application held by a person ?

The backend serving this API has access to the wallet storage (of a single or N users) ? can a cloud-wallet-sort-of service expose these API's for its clients (users) to access?

Is my understanding correct for the following?
- [/credentials/derive](https://w3c-ccg.github.io/vc-api/#derive-credential) - client (the holder wallet app?) will call this if he/she wants to derive a VC (selected disclosures) where fields comes from the `frame` field and the source VC to be derived  comes from `verifiableCredential`? .. a derived-VC will be returned?
- [/presentations/prove](https://w3c-ccg.github.io/vc-api/#prove-presentation) -  I don't quite understand what this API is for, who calls it and for what purpose?
- [/presentations/available](https://w3c-ccg.github.io/vc-api/#presentation-availability) - This API returns all the matching VC's based on the provided query? I'm imagining the logic in the backend of this API has access to the storage/keys of the particular requesting user?
- [/presentations/submissions](https://w3c-ccg.github.io/vc-api/#submit-presentation)- This API can help the wallet construct the Verifiable Presentation, where the result of the API call can be shared back to the requesting party (maybe a Verifier/RP)?

Thanks for anyone in advance who can answer my inquiries.

**Comment by OR13** [comment]
This WG has decided not to address authn / authz... Thats why you don't see any auth configuration in the OAS3.0 files.

We have a profile of the api that is attempting to address these concerns here:

https://github.com/w3c-ccg/traceability-interop/pull/131

This assumes that the entity invoking the API in an OAuth2 client.... obviously you would want to scope that client to only the activities it was allowed to perform.

I would recommend avoiding `derive` and `frame`, they are pretty unstable.

`presentations/prove` is to VPs and `credentials/issue` is to VCs... its how you get a VP with a proof on it from an api.

`presentations/available` and `presentations/submissions` are VP-Request-Spec over HTTP... you need to call `presentations/prove` in between to add proof over the challenge returned by `presentations/available`... its notable that those are 2 different security contexts with separate authorization considerations.

Feel free to reopen, or raise new issues if this answer is insufficient.
