### ISSUE TITLE
There should be a test that confirms a 4xx error when a credential issuance is requested with an unsupported issuer

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/vc-api#275]
See https://github.com/w3c-ccg/vc-api/issues/265#issuecomment-1073978994.

> The credential should be rejected with an error indicating that the issuer does not match. This results in a fail-closed scenario, which is preferable given the security context/purpose of VCs.

**Comment by OR13** [comment]
This issue is probably on the wrong repo since we split the tests out.

Unless we want to maintain the test plan in the current repo.

I would favor english sentences for all tests before attempting to write any tests.

**Comment by msporny** [comment]
The group discussed this on 2022-06-14 and it was suggested that if a PR is provided to not allow setting `issuer` on the issue request per https://github.com/w3c-ccg/vc-api/issues/265, then it would be impossible to get yourself into a situation where you send the wrong issuer to the VC API.

This issue can be closed when a PR is merged to remove `issuer` as an option that can be set to the issuance API.

**Comment by msporny** [comment]
The group discussed this during 2014-01-23 call, the expected PR:

* Throw a 400 `Bad Request` error if `issuer` is specified and the `issuer` value is not an expected value.

@mburchil volunteered to raise this PR.

**Comment by wes-smith** [comment]
Addressed by #365.
