### ISSUE TITLE
Need to address CI

### ISSUE THREAD

**Issue by mprorock** [w3c-ccg/vc-api#277]
need to adjust CI now that we can have unified UX for open api specs - see [this action fail for details](https://github.com/w3c-ccg/vc-api/actions/runs/2059943118)

@brownoxford - is this something you would want to take a look at, or will this need secrets access from someone like @msporny

**Comment by msporny** [comment]
> @brownoxford - is this something you would want to take a look at, or will this need secrets access from someone like @msporny

I've given @brownoxford admin access to this repo.
