### ISSUE TITLE
List of VC API implementations?

### ISSUE THREAD

**Issue by dmitrizagidulin** [w3c-ccg/vc-api#278]
During the CCG call earlier today, people expressed interest in getting an idea of the current VC API implementations out there (especially open source ones).

Please leave a comment here on this issue if you know of a VC API implementation.
(Maybe we can move that list to the README.)

**Comment by clehner** [comment]
- DIDKit (didkit-http) https://github.com/spruceid/didkit/tree/305481916434f97183c783106aff6f3f0056486c/http#api

**Comment by mkhraisha** [comment]
* api did actor by transmute is a wonderful one https://api.did.actor/

**Comment by aljones15** [comment]
This is what we're using for the current VC API test suites: https://github.com/w3c-ccg/vc-api-test-suite-implementations

**Comment by msporny** [comment]
The group discussed this on 2023-03-21:

We have a list of implementations in the test suite implementations repo here: https://github.com/w3c-ccg/vc-api-test-suite-implementations/tree/main/implementations

The group notes that that is the latest list of implementations that attempt to conform to the API.
