### ISSUE TITLE
How are client features requested by the server during exchanges using VPR?

### ISSUE THREAD

**Issue by msporny** [w3c-ccg/vc-api#280]
When a server is interacting with a client, it is often useful for the server to convey a set of features that it expects the client to have in order to complete a particular flow. 

Some protocols, such as TLS, [announce the client features](https://datatracker.ietf.org/doc/html/rfc8446#section-4.1.2) at the beginning of a protocol flow. Others, such as WebRTC start with a default, but [allow real-time negotiation of codecs](https://www.w3.org/TR/webrtc/#dom-rtcpeerconnection-createoffer) during a protocol flow. It's been suggested that VC API servers should publish their configurations via .well-known locations, others have suggested that an OIDC discovery endpoint should be used. Each of these mechanisms have benefits and drawbacks.

This issue discusses how such client features are expressed during exchanges that utilize Verifiable Presentation Requests. The initiation of an exchange typically starts in this manner:

```mermaid
sequenceDiagram
    participant WS as Wallet Service (backend)
    participant WA as Wallet App (frontend)
    participant IA as Issuer App (frontend)
    participant IS as Issuer Service (backend)
    autonumber
    WS->>IS: Initiate exchange via POST .../exchanges/{exchange-id} (VC-API)
    IS->>WS: DID Auth Request (VC-API + VPR)
    WS->>IS: DID Auth Response (VC-API + VP)
    IS->>WS: Exchange finalization or continuation (VC-API + VP)
```

Step 2 typically results in a VPR in the following format (note the `verifierSupportedCryptosuites`) value:

```
{
  query: [{
    type: 'DIDAuth',
    acceptedDidMethods: ['did:key', 'did:web', 'did:v1'],
    acceptedCryptosuites: [{
      type: 'DataIntegritySignature',
      cryptosuite: ['eddsa-2022', 'bbs-2022']
    }, {
      type: 'JWT',
      cryptosuite: ['Ed25519', 'P-256']
    }]
  }],
  challenge: '99612b24-63d9-11ea-b99f-4f66f3e4f81a',
  domain: 'exchange.example'
}
```

This is the general mechanism used by VPR to convey expected client features from the server to the client. New client features can be requested by each query language, at each continuation, for a particular exchange protocol. The benefit is that client features are limited to a particular step in the exchange, the drawback being that a client might not be able to fully complete an exchange if a client discovers that it does not have a particular feature halfway through the exchange. The latter issue can be mitigated by requesting a full set of features from the client at the start of the protocol. The benefit is that a server will know that a client can fully complete a given exchange, the drawbacks are leaking private information about features that the client might not want to broadcast to a server and the server blasting a client with every possible combination of client features required to get through every possible flow when only a subset is needed by a client for its particular use case.

What are the concerns with this approach wrt. specifying expected client features during exchanges?

**Comment by tplooker** [comment]
I may be missing something but this model still seems incomplete. Negotiation is a two way street, this model looks to have defined a way for one party to express what they support (server), but what about the other party? Say server x supports 3 crypto schemes and client supports only 1 of them how does the client communicate that? Who should be making that decision even, should it be the client? Or the server, making it the responsibility of the client makes client implementations of this protocol more complex.

As a side note I disagree with negotiating this information within the bounds of the protocol itself rather than having pre-phases to the protocol (e.g well-known endpoints), the failure happens too late which can create both user frustration and security issues.

**Comment by msporny** [comment]
> I may be missing something but this model still seems incomplete. Negotiation is a two way street, this proposal looks to have defined a way for one party to express what they support (server), but what about the other party? 

Protocol negotiation is never a two way street... either the party you are interacting with supports the features you need to continue or they don't. With respect to Verifiable Credential exchange, it's only the Issuer or Verifier's preferences that are important -- if a client can't support the requested features, then the exchange cannot happen.

There are also privacy and fingerprinting implications to the client broadcasting every feature it supports vs. responding to only the features that a server requires for a particular interaction. The former allows for broad-scale fingerprinting (an anti-pattern), where the latter combats it.

> Say server x supports 3 crypto schemes and client supports only 2 of them, how does the client communicate that? 

The server says "I support any of these 3 crypto schemes" and the client responds by selecting any of them.

> Taking a step back even further, who should be making the decision of what the signature scheme used on the issued VC should actually be? Should it be the client as implied by the direction of this proposal? Or the server? Making it the responsibility of the client makes client implementations of this protocol more complex.

Step 2 above is the *server* specifying the allowable signature schemes, not the client. The client just picks from one in its response, or responds with a "XYZ not supported" error (TBD if we want to add that sort of response to the VC-API... we probably should, so that the server can keep track of how many wallets don't support the interaction it's requesting).

> As a side note I disagree with negotiating this information within the bounds of the protocol itself rather than having pre-phases to the protocol (e.g well-known endpoints), the failure happens too late which can create both user frustration and security issues.

The pre-phase you're suggesting is just running an initial DIDAuth that's tied to an MFA on the Issuer of some kind. Pre-registration uses the same primitives as above... the benefit of the approach suggested in this issue -- dynamic, privacy-preserving, server-driven negotiation in the allowable primitives  -- is that it's layered (and therefore decomposable into a pre-registration step if necessary), cacheable, and supports upgrading into other protocols (if necessary).

**Comment by tplooker** [comment]
> Protocol negotiation is never a two way street... either the party you are interacting with supports the features you need to continue or they don't.

Hmm, I'm not following this logic even in protocols where there is an asymmetry in the roles performed in the protocol negotiation (e.g one party always list whats it supports and the other picks - like TLS) that still requires information about the negotiation traveling in two directions (hence the two way street analogy).

The point im trying to make is it looks like you have defined the `server -> client: hey heres what I support` equivalent but where is the `client -> server: cool lets use this one` step? Or is it not required, if not how is the selection done and communicated back to the server?

> The pre-phase you're suggesting is just running an initial DIDAuth that's tied to an MFA on the Issuer of some kind. Pre-registration uses the same primitives as above... the benefit of the approach suggested in this issue -- dynamic, privacy-preserving, server-driven negotiation in the allowable primitives -- is that it's layered (and therefore decomposable into a pre-registration step if necessary), cacheable, and supports upgrading into other protocols (if necessary).

No what Im saying is most of the information like the did methods and signature schemes the server supports is not really conceptually related to the DIDAuth request IMO and transmitting it in every DIDAuth request feels quite redundant. I understand the point of view around potential privacy benefits w.rt the client not transmitting everything it supports. But I dont see how any of this information will be super dynamic, I see it being information that changes at a similar cadence to algs and response types supported by an IDP, hence why I tend to favour the .well-known style solutions to publishing this information as is popular in OIDC and OAuth2.

**Comment by msporny** [comment]
The group discussed this on the 2022-11-01 call. @msporny provided some background. @dlongley wanted to frame the issue differntly - The server is basically saying "These are the things I accept, you choose things from that list, if you don't have something on that list, we're not compatible." If there are a set of things that are not a part of the protocol, if issuer wants to make sure you can do certain things, client can respond by saying "here's a VC from some 3rd party saying that I meet your requirements". You can either respond back by using a particular protocol, or that and a set of credentials. in all cases, having the issuer say "I will accept this stuff" and then saying "you choose" avoid the fingerprinting problem. @PatStLouis asked if when we talk about this -- "What I need?" or "What I can do?". @dlongley noted that in this case, we're talking about Verifier asking someone to do a DID Authentication, they're saying: "I want you to do a DID AUthentication and here are the DID Methods I support and cryptosuites that I can support" -- it's really about what they can accept. @PatStLouis asked if this is endpoint-specific, or if this a discovery endpoint where you can filter results -- verifier, isn't this useful for issuer? @dlongley noted in context of Issuer, when Issuer is playing role of Verifier -- authenticating the holder, for example. Generally, when party is playing role of Verifier is where this is useful. @PatStLouis asked if this is specifically scoped for authentication. @dlongley noted that when you're asking another party for a VP, you're asking them to provide you with VCs you have, usually you want an authentication proof over entire presentation, or some other field bound to user in your system. This seems very much associated with authentication. @PatStLouis asked if this is used programmatically, or discovery with documentation URL and implement this and correctly work w/ agent, or worked in process every time and take action based on return? @dlongley This is mostly the latter, programmatic -- someone wants to do a DID Auth, Verifier askes DID Auth first, in protocol message. Client will process that, offer user some choices, but then responded to.

The group will continue discussion on this item next week...

**Comment by msporny** [comment]
We discussed this on the 2022-11-08 telecon and picked up the conversation. @mavarley noted that the OIDC4* mechanism uses a static list and makes a decision on the static list of features. Checking if they are compatible w/ provider, decision is made on whether it wants to continue. The VC API attempts to make decisioning to be more dynamic and features are more transactional in nature. @dlongley noted an added advantage for VC API is you might have different requirements based on different credential types, different types based on DID methods... for example, proving you can do BBS Signatures for a specific type of credential. Unless static metadata would allow granular, detailed information around each credential type and if every credential type is public information, you couldn't get to feature parity there. @dlongley noted that so far, VC API is more flexible in allowing multiple vendors to allow multiple backends to an issuing party -- using multiple vendors on the backend, easier to create based on round-robin'ing mechanism -- easier to do without having vendors to coordinate around having single metadata file. There might be ways to get this to work with OIDC4VCI, but we do know that we can do this with VC API today -- avoid vendor lock in and need for vendors to coordinate more to make that work.

@msporny asked that since we have a mechanism using VPR that does this today and has been interop tested, do we want to use another mechanism? @dlongley noted that you can use VPRs on dynamic requests for features -- where does this issue belong, VPR is the primitive or message that can be used to travel across VC API. If other people come up with other types of messages, they could be used here, but at present VPR is the only mechanism that exists.

The group notes that there is a mechanism to express acceptable client features today using VPR that is documented for DID Authentication (in the VPR specification) and has multiple interoperable implementations through JFF Plugfest 2. The group is open to other mechanisms if they arise, and if they do, we will discuss those as separate issues.

This issue will be closed as resolved in 7 days unless there are objections.
