### ISSUE TITLE
npm run build fails without dependency

### ISSUE THREAD

**Issue by paulfdietrich** [w3c-ccg/vc-api#293]
May have been obvious to others, but I had to 

```
npm i @openapitools/openapi-generator-cli
```

before npm run build would bundle the API. Might be worth mentioning for openAPI newbies.

**Comment by msporny** [comment]
We need to add the openapi-generator-cli to the package.json file.

**Comment by msporny** [comment]
We need to see if anyone is using the pure openapi files anymore. If not, we could remove this feature.

**Comment by BigBlueHat** [comment]
FWIW, this worked fine for me just now _without_ adding the `@openapitools/openapi-generator-cli`, so I think this can be closed. 

It's likely that an upstream package fixed their dependency chain which solved it here also...perhaps.

**Comment by msporny** [comment]
@paulfdietrich can you confirm, please?

We will close this in 7 days if we don't get a response.
