### ISSUE TITLE
Should the VC API support callbacks?

### ISSUE THREAD

**Issue by msporny** [w3c-ccg/vc-api#295]
There are times where it might be appropriate for the VC API to use callbacks. Two use cases are:

1. Report to an external system on progress, such as the issuance of a VC.
2. Retrieve data from an external system to use in an exchange.

Consider the following diagram:

```mermaid
sequenceDiagram
    participant WS as Wallet Service
    participant IA as Issuer App (Business Logic)
    participant PS as Presentation Service
    participant IS as Issuer Service
    autonumber
    WS->>PS: Request VC (VC-API)
    PS->>WS: Request authentication (VC-API + VPR)
    WS->>PS: Provide authentication (VC-API + VP)
    PS->>IA: Retrieve data needed for VC
    PS->>IS: Issue VC (VC-API)
    IS->>PS: Issued VC (VC-API)
    IS->>IA: VC has been issued (VC-API)
    PS->>WS: Issued VC (VC-API + VP)
    PS->>IA: Exchange has been completed (VC-API)
```

Steps 4, 7, and 9 are callbacks that might be useful for the services defined by the VC API. Thoughts?

**Comment by msporny** [comment]
This was discussed on the 2022-07-12 call. [[LINK HERE]]

**Comment by msporny** [comment]
With respect to the concept of a "Presentation Service" vs. an "Exchanger Service" ... @dlongley suggested that we have two classes of services. @jandrieu mentioned "Presentation Service" is "Holder Service" (credential derive, create, and get). @David-Chadwick noted that OIDC flows integrate tokens for issuing and refresh into Holder service.

What we might need is the concept of a "Holder Service" and a "Exchanger Service" (which might be absorbed by the Issuer App in some cases).

**Comment by dlongley** [comment]
A PR should definitely specify how to return a `redirectUrl` at the end of an exchange for a client to use / get back into the channel where an exchange started. Doing web-hooks, etc. is much more open-ended and we need polling to work whether or not push notification style optimizations can be used.

**Comment by msporny** [comment]
The group discussed this on the 2024-01-23 call:

@dlongley noted that there are two different ways callbacks can be supported:

* Optionally, return a redirect URL at the end of an exchange that could be included in the final response at the end of an exchange which would be optionally followed by client doing the exchange. That could be helpful for binding something back to a channel where it originated.
* Other types of callbacks could be sending back-end messages (not re-directs), but "push notifications" (aka web hooks) during an exchange. These types of systems need to be resilient (failure to deliver) and so you'd need some kind of polling mechanism to get state of an exchange. Specifying that now might be more about optimization in an optimistic case (but still need polling).

It's not clear what text to write for the "web hook" piece. It's clear what would need to be written for "redirect URL" and "poll" (where web hooks would be an optimization on top).

@mbuchil said that many of these things are defined outside of the API, might be a slippery slope to dictate how this works. @jandrieu noted he likes web hooks, but we do need to figure out polling (to deal w/ failure). Could use notion for "interact" to frame how web hook could be done. @PatStLouis noted that there could be a "/web-hooks/" endpoint.  @jandrieu noted that other constraint we could provide -- web hooks could be provided by coordinators (so we could focus our efforts there wrt. what to define.

It was decided that the group would try the most straightforward approach first, which is to provide a redirect URL first and then a few paragraphs around considerations wrt. web hooks vs. polling.

**Comment by msporny** [comment]
The group discussed this on 2024-05-28 call. 

@dlongley recommended closing #295 and keeping issue #347 since it's more specific. The most useful place to put callbacks right now is in exchanges. @jandrieu +1 to solve the more specific use case (this issue). @PatStLouis reading #295, use case identified, report to external system on progress in an exchange, somewhat of a different use case. Make sure threads in other issue are captured here. @dlongley didn't think that there is a use case to report back on progress of issuance (atomic operation of issuance API). Use cases are around exchanges, other issue has been opened for a long time, it's still open/linked if it's not exchange related, let's close to make progress. @jandrieu noted that point of exchanges is to be abstraction, right layer to handle callbacks in general, this isn't just simpler use case, among APIs that are synchronous, we can move async stuff to exchanges (where all callback stuff moves).

The group decided to focus the callback URL discussion wrt. exchanges in issue #347 and close issue #295 because it was believed that by addressing callbacks in exchanges that it would address most, if not all, callback use cases.
