### ISSUE TITLE
404 HTTP error response status

### ISSUE THREAD

**Issue by artursudnik** [w3c-ccg/vc-api#305]
Hi,

I am curious if there is a reason why the `404 Not Found` response is not listed for example for https://w3c-ccg.github.io/vc-api/#continue-exchange endpoint at all? It would be a very standard and intuitive way of providing feedback if a non-existing `exchange-id` or `transaction-id` is provided in a request.

**Comment by artursudnik** [comment]
Some relevant discussions:
https://stackoverflow.com/questions/25378624/should-a-restful-api-return-400-or-404-when-passed-an-invalid-id

**Comment by aljones15** [comment]
@artursudnik 404 was added to continue exchange in v0.3 of the API. Can this issue be closed?

**Comment by artursudnik** [comment]
@aljones15 Yes of course! Thank you very much!

**Comment by ottonomy** [comment]
404 is a relevant response code for [Get A Specific Credential](https://w3c-ccg.github.io/vc-api/#get-a-specific-credential) as well. `410 Gone` is only appropriate if the server knows the resource once existed and no longer does.
