### ISSUE TITLE
Define schema for response of /credentials/issueCredential

### ISSUE THREAD

**Issue by llorllale** [w3c-ccg/vc-api#33]
Can we agree on a basic schema for this object?

https://github.com/w3c-ccg/vc-issuer-http-api/blob/5ccd7d96e9f3e52777e7c63c9253a4d8e47a4fe4/api.yml#L39-L40

Keeping the mime type as `application/json`, this would imply an object that looks roughly like this:

```json
{
    "ref": "9255b830-53c2-43db-83b5-5b436c91ab59",
    "credential": {
        // JSON-LD VC credential with proof
    }
}
```

**Comment by msporny** [comment]
The group discussed this on 2021-06-22 and believes that this issue is stale. Next step is to refer to resolutions or code commits that addressed the return value of issueCredential.

**Comment by msporny** [comment]
Defined in https://github.com/w3c-ccg/vc-api/blame/main/issuer.yml#L32. Closing.
