### ISSUE TITLE
updateCredentialStatus PATCH instead of POST?

### ISSUE THREAD

**Issue by nissimsan** [w3c-ccg/vc-api#339]
Looking at https://w3c-ccg.github.io/vc-api/issuer.html#tag/Credentials/operation/updateCredentialStatus, it seems like a PATCH operation would be better suited than the current POST?

**Comment by msporny** [comment]
The group discussed this on 2023-07-18:

@dlongley noted that PATCH is typically used when you have a resource which has a stable state that you're updating (like updating a JSON object). PATCH presumes consistent resource representation across all implementations, presuming JSON and JSON Patch. Don't know if that's the case here, and using PATCH might be more prescriptive than we want to be. In order for us to use PATCH properly, whatever the result of the PATCH is, we would have to be modifying the document directly as JSON, which might imply being able to do additional constraints on what operations can be run in the patch vs. "there is a POST body and you send the status you want". There are heavier weight requirements around using PATCH vs. using POST that is functional, send parameters and expectations for what would happen when you're done (feels lighter weight for now). 

@msporny noted that we can always implement PATCH later. The operations we want to do for now sound like higher-order operations (not just modifications to JSON entries).

The group decided that they'd continue to think about how PATCH could be used here and would come back to thinking about implementing it if we had multiple implementers that have implemented PATCH in the same way. Closing for now given that we don't have enough implementation experience on directly modifying JSON via PATCH for VCs.
