### ISSUE TITLE
Atomicity of credential issuance and reference creation

### ISSUE THREAD

**Issue by troyronda** [w3c-ccg/vc-api#34]
Moved discussion from https://github.com/w3c-ccg/vc-issuer-http-api/pull/43#issuecomment-598896804

@dlongley wrote:
> That's right. Nothing is stored on the server without it also having been issued and there's no option to only issue a credential without storing a reference to it. If you want or need to use another service to compose the credential via a template/other options before submitting it to be issued, the /credentials/compose method can be used if made available by the implementer.

@troyronda wrote:
> @dlongley Ok that makes sense under those assumptions.
> Are there alternative situations where:
> * a separate system is responsible for storing the credential references? if so, they might want a /credentials that has a fully issued credential in the payload.
> * someone is not planning to store the credential reference.

> (those scenarios could impact the consistency of a combined issue + store operation on /credentials)

**Comment by OR13** [comment]
I would close this issue, since templates / incremental credential building would appear to be out of scope for the current API design.

**Comment by msporny** [comment]
This issue was discussed on the telecon today, and the following resolution was approved:

RESOLVED: Regarding issue https://github.com/w3c-ccg/vc-http-api/issues/34, if a caller desires to build a VC incrementally of from a template, the caller can use another API to do so and then send the fully formed VC to the VC HTTP API for processing.

**Comment by msporny** [comment]
The group discussed this on 2022-03-29 and decided that it wasn't useful to add the text resolved above. Closing without any changes to the specification.
