### ISSUE TITLE
Microsoft calls their REST API "VC API"

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/vc-api#342]
- https://aka.ms/vcapi

Not sure if this has been raised before, but this kind of name collision will cause developers confusion.

**Comment by brianorwhatever** [comment]
I also don't see any references to VC API at Microsoft. Recommend closing this as unless we can find a reference to the collision there is no issue here.

**Comment by msporny** [comment]
The group discussed this on the 2023-08-01 call and looked at the documentation at the link provided in the issue. There is no mention of "VC" or "VC API" in the documentation. The group felt like this issue has been addressed on the Microsoft website. Closing.
