### ISSUE TITLE
Update derive endpoint for compatibility with current selective disclosure specifications

### ISSUE THREAD

**Issue by Wind4Greg** [w3c-ccg/vc-api#363]
There are currently two VC specifications in process that support selective disclosure: [Data Integrity ECDSA Cryptosuites v1.0](https://w3c.github.io/vc-di-ecdsa/) and [BBS Cryptosuite v2023](https://w3c.github.io/vc-di-bbs/). Currently the derive endpoint supports the following properties: `verifiableCredential`, `frame`, and `options`.

Neither selective disclosure specification utilizes JSON-LD framing anymore hence the `frame` field should be deprecated. Instead both specifications use `selectivePointers`, an array of JSON pointers, to specify selectively disclosed claims. 

Based on discussions on the 2024-01-30 VC-API call it was suggested that a `selectivePointers` attribute be added to the `options` property to accommodate selective disclosure via the current specifications.

**Comment by msporny** [comment]
This issue was addressed via PR #367, closing.
