### ISSUE TITLE
Update issue end point to support selective disclosure mandatory option

### ISSUE THREAD

**Issue by Wind4Greg** [w3c-ccg/vc-api#364]
There are currently two VC specifications in process that support selective disclosure: [Data Integrity ECDSA Cryptosuites v1.0](https://w3c.github.io/vc-di-ecdsa/) and [BBS Cryptosuite v2023](https://w3c.github.io/vc-di-bbs/). The issue endpoint supports the `credential` and  `options` properties.

As part of an issuer creating a "base proof" it is required that an array (possibly empty) of `mandatoryPointers` be input  (see https://w3c.github.io/vc-di-ecdsa/#base-proof-transformation-ecdsa-sd-2023) to specify which statements must be disclosed by a holder when creating a derived credential.

Specifying the `mandatoryPointers` can be done via configuration, but it is also be desirable as an optional input as a field of the `options` property.

**Comment by msporny** [comment]
This issue was addressed via PR #367, closing.
