### ISSUE TITLE
How do we deal with expiry on Challenges/Exchanges?

### ISSUE THREAD

**Issue by mkhraisha** [w3c-ccg/vc-api#374]
coming out of #373 

Should we have a section that outlines how challenges are expired?

some ideas discussed on the call:

1. We can have an expiry time returned at challenge creation.
2. We can have a TTL on the exchange itself, without a need to signal how the expiry time of the individual challenge.

Things to note: an exchange may have multiple challenges, and may need a longer TTL than would be acceptable for a challenge timeout.

**Comment by msporny** [comment]
The group discussed this on the 2024-05-28 telecon:

@dlongley noted that we have the concept of TTLs for exchanges, need to document that more in the spec. If that's sufficient, we can leave it at that until we find out that it's not sufficient. All that matters is probably how long exchange lives and if challenge is for an exchange, it's lifetime is bound to that exchange.

The PR that is raised should add a few sentences to the specification noting the above about TTLs and exchanges (if it's not already in the specification).
