### ISSUE TITLE
Change `verifiedCredential` to `credential` for symmetry

### ISSUE THREAD

**Issue by dlongley** [w3c-ccg/vc-api#381]
See: https://github.com/w3c-ccg/vc-api/blob/ffe5571e7213253e43dd35a4d4e713f2b9011581/components/VerificationResult.yml#L35

**Comment by wes-smith** [comment]
The group discussed this on the 04-30-2024 call and decided that the property name should be `credential` to cover all potential use cases.

**Comment by msporny** [comment]
PR #388 has been mer
