### ISSUE TITLE
mis-tweaked #400

### ISSUE THREAD

**Issue by TallTed** [w3c-ccg/vc-api#401]
https://github.com/w3c-ccg/vc-api/blob/5d12fbef8c86c9c355ea81fefd0fcde63ee0fd36/exchanges.yml#L134-L136

Rereading the discussion, I think I mis-tweaked the language (and missed that the first line in the paragraph also needs tweaking) in #400.

Note that by posting an empty body, the client is not making any conformable request.

I *think* this would be a better conclusion, fixing the whole paragraph.
```
      summary: Participate in an exchange. Posting an empty body to start
        the exchange will result in a Verifiable Presentation, a Verifiable 
        Presentation Request, or a 4xx error.
```
Tagging @wes-smith @msporny @dlongley

**Comment by wes-smith** [comment]
Fixing in my changes.
