### ISSUE TITLE
Paragraphs in "Storage Services" section are put in "Workflow Service" section?

### ISSUE THREAD

**Issue by laysakura** [w3c-ccg/vc-api#404]
I guess these two paragraphs:

https://github.com/w3c-ccg/vc-api/blob/066f0309d2c5e8b5a2bc972a0a60464c805e1705/index.html#L479-L499

should be placed into the ["Storage Service" section](https://github.com/w3c-ccg/vc-api/blob/066f0309d2c5e8b5a2bc972a0a60464c805e1705/index.html#L461C13-L461C29) (, which is currently empty).

**Comment by msporny** [comment]
The group discussed this on the 2024-07-23 telecon:

There are some markup errors that have led to the text in the document being corrupted. We should fix the markup errors.

A PR should be raised to fix the markup errors pointed out by @laysakura.
