### ISSUE TITLE
API to support Issuer HTTP API to call out directly to subject datastore

### ISSUE THREAD

**Issue by mavarley** [w3c-ccg/vc-api#41]
The current API and Architecture does not support an Issuer Service providing the 'Subject' as a parameter and then allowing the Issuer HTTP API to reach out to a subject data store to directly collect the claims.

This design pattern may be beneficial for Issuer Application logic, and may also provide a security benefit (because there are less intermediaries handling the subject claim data).

@David-Chadwick @peacekeeper to expand.

**Comment by peacekeeper** [comment]
I think we need to revisit this issue, I propose we re-introduce the `subjectReference` parameter from the v0.0.0 API: https://github.com/w3c-ccg/vc-http-api/blob/master/docs/versions/v0.0.0/vc-http-api.yml#L60

@mavarley @gannan08 @msporny

**Comment by OR13** [comment]
@peacekeeper can you provide additional documentation for the proposal on this issue? what is `subjectReference` how should it be used? 

Pulling from the link you provided:

> Optional internal reference to the subject for which to issue a credential. If this is present, it may be used to pre-populate certain fields in the request body (e.g. "claims" and/or "subject").

Seems like subjectReference ~= jwt.sub ?

**Comment by peacekeeper** [comment]
> what is `subjectReference` how should it be used?

It's an internal reference that an implementation of the VC HTTP API can use to fetch claim data from some internal data source (how exactly that works is out of scope). A caller of the VC HTTP API would send a `credentialSubject` that is empty (well, except for the `id`), plus a `subjectReference`.

The contents of the `credentialSubject` are not provided by the client, but inserted server-side by the VC HTTP API implementation, which uses the `subjectReference` to look up the data.

I can attempt a PR if others also see a need for this.

**Comment by OR13** [comment]
lets keep discussing on the issue for now,

so essentially it would work something like this:

```
const claims = await getClaimsBySubjectReference(subjectReference);
const credentialWithClaims = {
...credential,
credentialSubject:{
...credential.credentialSubject,
...claims
}
}
const vc = issue(credentialWithClaims, {options: suite, documentLoader})
```

**Comment by peacekeeper** [comment]
I agree with your code..

> How do you know which claims should be included?

I'd say that's implementation-specific, but I imagine it would work by passing the `credential.type` (or the entire `credential` minus the `credentialSubject`) as input to the `getClaimsBySubjectReference` function.

**Comment by OR13** [comment]
hmmm, I like the idea of passing the credential type / context.... that seems like a good way to look up claims that could be mapped... this is starting to feel like something that might be better if it directly mapped to JSON-LD Frame and / or the Presentation Exchange Spec.

**Comment by OR13** [comment]
This issue has been over taken by events, and we have decided not to build APIs that help folks make JSON-LD great again.

**Comment by msporny** [comment]
We discussed this on 2021-11-16. The group believes that this has to do with composition APIs and that we've put composition APIs out of scope at this point in time. There was no objection to closing the issue.

**Comment by TallTed** [comment]
> [@OR13] [we have decided not to build APIs that help folks make JSON-LD great again](https://github.com/w3c-ccg/vc-api/issues/41#issuecomment-970701102)

I have significant issue with the above comment, not only because I think JSON-LD is, was, and will remain great for many uses, regardless of whether it could have or will ever be put to use here.

The quoted phrase above was not what I was thinking when we decided that ["this has to do with composition APIs and that we've put composition APIs out of scope at this point in time"](https://github.com/w3c-ccg/vc-api/issues/41#issuecomment-970701453), and I daresay there will be others who were on the call and disagree with that phrasing.
