### ISSUE TITLE
Consider downsides of RESTful APIs

### ISSUE THREAD

**Issue by peacekeeper** [w3c-ccg/vc-api#50]
@dhh1128 has highlighted several downsides of using a RESTful approach for a VC issuing API, including:

1. RESTful APIs are web-only.
2. RESTful APIs perpetuate the PKI model that we claim to be replacing with DIDs.
3. RESTful APIs foster a power imbalance.

If possible, those should be addressed in the API design.

For the full details including potential alternatives, see https://lists.w3.org/Archives/Public/public-credentials/2019Dec/0072.html.

**Comment by OR13** [comment]
I suggest closing this issue, we are building an http api.

**Comment by dhh1128** [comment]
I am willing to have the issue closed. I disagree with the design choice to frame this effort through an HTTP lens -- but having made that decision, I agree reasoning from @peacekeeper and @OR13 that this issue becomes less relevant.

**Comment by peacekeeper** [comment]
Also wanted to mention that the group recently voted to rename "VC HTTP API" to "VC API" (although we still need to execute that change in the various repos and files):

https://w3c-ccg.github.io/meetings/2021-09-21-vchttpapi/#topic-3

**Comment by msporny** [comment]
@dhh1128 wrote:
> I am willing to have the issue closed. I disagree with the design choice to frame this effort through an HTTP lens -- but having made that decision, I agree reasoning from @peacekeeper and @OR13 that this issue becomes less relevant.

Based on this comment, closing this issue.
