### ISSUE TITLE
batches

### ISSUE THREAD

**Issue by jchartrand** [w3c-ccg/vc-api#51]
Sometimes credentials are issued in batches (e.g., university degrees), and each individual credential might in fact include some detail about the batch (like a merkle root or a blockchain transaction reference), implying therefore that we have to process the whole batch at once?   

Maybe the POST /credential could take an array of creds, so they all get processed at once?

Or there could be a 

POST /credentials 

that takes an array?

And, a corresponding api call to update the status of the batch as a whole (say if the key used to issue the batch was compromised, or there was some other problem with the entire batch, e.g., a typo on the degree name).  So maybe something like:

POST /credentials/{batchReference}/status

The batchReference could be the issuing/signing public key if a key is only ever used for a single batch.

**Comment by OR13** [comment]
I am self assigning and will take a stab at a PR to address this issue

**Comment by OR13** [comment]
```
POST /batch/credentials/issue

```

**Comment by OR13** [comment]
```
POST /credentials/batch/issue
```

**Comment by OR13** [comment]
```
POST /batches/credentials
```

**Comment by tplooker** [comment]
@OR13 considering the conventions you have set out in #73 perhaps we could opt for a model where the POST `credentials/issue` endpoint is instead polymorphic e.g it accepts either an object or an array of objects in the request body?

**Comment by OR13** [comment]
perhaps it would be better to just always batch I am not a huge fan of polymorphic http interfaces.

**Comment by peacekeeper** [comment]
If the only difference of "batch" is that it issues multiple credentials instead of one, then I think simply passing an array to the existing endpoint makes most sense.

If "batch" has some additional semantics such as running some kind of internal pre-processing or data fetching logic, then perhaps a new endpoint is better.

**Comment by OR13** [comment]
I suppose one question is, should it be possible to post a path with unique options per vc? my sense is the answer should be no.

**Comment by jchartrand** [comment]
What would be an example of a unique option per VC?  Different credential name maybe, like Bachelor of Science vs. Bachelor of Science Honours vs. Bachelor of Arts, etc.?

**Comment by OR13** [comment]
yes, and possibly different issuers, for example, MS / BS from different issuers.

**Comment by jchartrand** [comment]
Looking at this only for degrees (i.e., higher-ed) I would guess that some schools would be okay with separating what would be considered a 'batch' (e.g, Spring Convocation) into separate POSTs -  but some would want to keep it altogether as a single batch, possibly for different reasons: easier to manage a single batch than many, easier to revoke or redo a full batch vs. hundreds of smaller ones (although you could just as easily imagine a scenario where smaller batches would help when wanting to revoke just a subset), cost (e.g, if using a public blockchain like Bitcoin for timestamping/proof where each transaction could be costly), etc.

I guess a relevant question is:  does the POST take an array of preconstructed VCs (without signatures) and then dates/signs them accordingly, in which case any VC-specific options would be handled by whoever constructs the unsigned VC *before* it ever gets POSTed, or does the POST take metadata in something like a CSV/XML/JSON format and both construct the VC and sign it (in which case the CSV/XML/JSON might end up having to account for all sorts of variations that might make it unwieldy)?

The different-issuers-in-one-batch problem that you describe seems like it could get very complicated, dictating which signing key is to be used for which credentials, etc.?

**Comment by OR13** [comment]
> I guess a relevant question is: does the POST take an array of preconstructed VCs (without signatures) and then dates/signs them accordingly, in which case any VC-specific options would be handled by whoever constructs the unsigned VC _before_ it ever gets POSTed,

This is the behavior of the current issuer api, yes.



> or does the POST take metadata in something like a CSV/XML/JSON format and both construct the VC and sign it (in which case the CSV/XML/JSON might end up having to account for all sorts of variations that might make it unwieldy)?

this is the behavior of our planned / non stanstandards wrapper... if we could get consensus on how to support CSV / Templates, and metadata, IMO it would be a major improvement to these APIs, but this was a point of contention previously.



> The different-issuers-in-one-batch problem that you describe seems like it could get very complicated, dictating which signing key is to be used for which credentials, etc.?

Yes, that is the risk of per credential options... but note that its similar to the "credential meta data" problem... I don't see a way to avoid data about an issuance that goes along with the credential issuance, but not in the credential itself.

**Comment by jchartrand** [comment]
Ah, I see.  So the templates you mention would be VC templates with 'placeholders' into which the issuing service inserts data from an accompanying CSV (like the recipient's name, DID, etc.)?

And so I guess the signing key to be used for a given credential could similarly be listed per row in the CSV, to be inserted into the proof:

```
"proof": {
    "type": "${comes from a row in the CSV?}",
    "proofPurpose": "${comes from row in the CSV?}",
    "verificationMethod": "${this comes from row in the CSV}"
  }
```

I guess that would often make for a lot of duplication (e.g., the same signing key listed for many/all of the rows), but maybe that's okay?

Out of curiosity, where does the private key come into play?  Where is it stored, and how is it pulled into the API at issuance time?

**Comment by OR13** [comment]
hmm, a couple things here...

I am not asserting anything particular in my response, just a descriptions of some likely requirements we need to get agreement around.

1. Batching many credentials to be issued in a single network request
2. Describing both metadata and credential data associated with each credential
3. Some form of "DRY" / "Templating" to cut down on the request size

Some combination of CSV or JSON Templating could solve for all of these.... the current APIs fail to meet these requirements IMO.

Regarding private keys, they are out of scope for these APIs, the assumption is that an API vendor "has a way to sign, and can expose identifiers it will use to sign"... nothing more regarding to lower level crypto.

**Comment by jchartrand** [comment]
Sorry, I should have said 'might be' not 'would be'.  I didn't mean to claim you'd said something you hadn't.

Interesting, though - I'd imagined that the templating  (point 3) wasn't so much about DRYing things out so as to cut down on request size, but instead about eliminating the need for issuers to pre-construct VCs, leaving that work to the API vendors, with the significant benefit that if the VC spec changed over time, then each issuer wouldn't have to update their VC generation code, but rather just the vendor (so DRY for a different reason).  Multiple DRY benefits then maybe.

**Comment by peacekeeper** [comment]
More recent discussions about batches are happening in https://github.com/w3c-ccg/vc-http-api/issues/87 and https://github.com/w3c-ccg/vc-http-api/issues/100. Maybe we close this older issue here and continue this topic in the newer issues?

**Comment by msporny** [comment]
We discussed this on 2021-11-16 and the group decided that batching is out of scope for this version of the VC API. Closing.
