### ISSUE TITLE
allow setting credential status before issuance to allow 'pre-registration' of credentials

### ISSUE THREAD

**Issue by jchartrand** [w3c-ccg/vc-api#52]
The POST credential/{credentialReference}/status definition says that the  'credentialReference' parameter is:

"Reference to a credential that has been issued."

There might be cases, though, where an issuance system sets the credential status before issuing the credential.  So essentially 'pre-registers' the credential, maybe as part of a security safeguard (to prevent internal fraudulent issuance) where one person pre-registers credentials (setting the status to 'pending'), and another (with separate authorization) issues the credential (setting the status to 'active')

'Pre-registration' maybe makes more sense if credentials are issued in batches ( I've suggested allowing batches in w3c-ccg/vc-http-api#51 ), so maybe then with something like:

POST /credentials/{batchSigningKey}/status

assuming a signing key is only used for a single batch.  And the status might be one of:

pending (i.e, the 'pre-registered' state;  the batch hasn't yet been issued)
active (the batch has been issued)
revoked (the entire batch is revoked)

**Comment by mavarley** [comment]
On the call on 05-01-2021, we discussed this issue and we didn't see (or understand properly) the need  to support this function in the API; @jchartrand @dhh1128 did you want to provide a use case for this feature and how it would work? Otherwise the issue will be closed out. Thanks.

**Comment by dhh1128** [comment]
Here is a concrete use case:

The credential to be issued is a complex and high-value one (e.g., a passport, a security clearance), where there is sophisticated workflow that must unfold over hours, days, or weeks between the time that issuance is requested and the time that issuance actually completes. In such a case, being able to model a "pending issuance" in the API could be useful.

I did not open this ticket, so my comment here is a direct response to @peacekeeper 's question, but does not necessarily mean I am advocating to keep the ticket open. A possible response to my use case would be: "That's out of scope. Call the API to issue at the end of that complex workflow. Don't call it at the beginning." I don't have a problem with that answer, *as long as we are clear that the API has made the design decision to deliberately preclude issuance process complexity.*

**Comment by mavarley** [comment]
> "That's out of scope. Call the API to issue at the end of that complex workflow. Don't call it at the beginning." I don't have a problem with that answer, as long as we are clear that the API has made the design decision to deliberately preclude issuance process complexity.

Thanks @dhh1128 - the use case clarifies the business process that may exist in issuing credentials where a credential may be in a 'pending' state, awaiting another action, to become active. The above proposal is _one_ way of approaching this case, but there could be many others (issuing different types of credentials for different uses, etc...). 

The design of the API has put other business-type processes out of scope at this time; like credential composition APIs for example.

I think this issue should be marked closed (won't address) with the caveat that if the community comes back around and sees a need for this functionality (as new specs and workflows are designed, this API may need to support this capability to support those workflows, without managing credential issuance processes).
 
So it is a "not right now" as opposed to a "not ever".

**Comment by jchartrand** [comment]
I think what I'd imagined (although explained poorly) was providing support for multiple signings (i.e., countersignings).  Possibly simply to get the security benefit of multiple signings (by different keys held by different people), but possibly also to indicate approval at different stages of issuance, so like:

1. a university generates a big batch of degrees (as VCs) at convocation, which have all been vetted and approved by the campus registrar, and so are signed at that time using the registrar's key/DID (asserting that the registrar approved the issuance).  We don't yet know the DID (or link secret) of each student, however, so we just store the signed VCs somewhere until the student provides a DID (link secret).

2. When the student wants to collect their degree they login to the campus system and provide a DID (link secret).  Now we can add the student's DID to the VC, and sign a second time (now asserting that the student's DID was confirmed via authentication on the campus system.)

I don't think what I'd suggested in the initial issue makes much sense for this case, though, because simply changing a status, without a signature, doesn't really provide these safeguards.

Anyhow, I can see this probably gets well outside the scope of the API (and that there are other complications like adding a subject DID to an already signed VC), so happy to have the issue closed.  Thank you nonetheless for giving it due consideration.

**Comment by peacekeeper** [comment]
@jchartrand do you have any updated thoughts on the discussion here? I realize you opened the issue long ago.

Are you okay with considering this to be out of scope (for now), and closing the issue?

**Comment by dlongley** [comment]
@peacekeeper,

In this [comment above](https://github.com/w3c-ccg/vc-http-api/issues/52#issuecomment-936268333) @jchartrand noted that they are "happy to have the issue closed".

**Comment by msporny** [comment]
> In this [comment above](https://github.com/w3c-ccg/vc-http-api/issues/52#issuecomment-936268333) @jchartrand noted that they are "happy to have the issue closed".

Based on this comment, closing.
