### ISSUE TITLE
Arbitrary validation of business rules

### ISSUE THREAD

**Issue by msporny** [w3c-ccg/vc-api#55]
@dhh1128 wrote:
> we're assuming that the verification service possesses all the necessary knowledge, connectivity, and context to do verification. But some kinds of verification may not be doable by a service (e.g., validate business requirements that only the client knows about). That's not necessarily a problem; I'm just saying that we should recognize the limits of the plugin validator model we're going with.

We should consider how a client may configure and trigger business rule checks on the verifier. This feels like a lot of work, and has a low probability of resulting in a standard mechanism, but should explore the topic in case someone proposes a mechanism that quickly garners consensus.

**Comment by peacekeeper** [comment]
We discussed this on the [05 Oct 2021 VC API Work Item call](https://w3c-ccg.github.io/meetings/2021-10-05-vchttpapi/) and felt that validation of business logic (e.g. evaluating if a VP matches a certain request) should happen outside of the API.

Also see https://github.com/w3c-ccg/vc-http-api/issues/59.

We therefore thought that this issue should be closed.

**Comment by msporny** [comment]
> We therefore thought that this issue should be closed.

￼Based on this comment, closing.
