### ISSUE TITLE
Add proof request as option

### ISSUE THREAD

**Issue by msporny** [w3c-ccg/vc-api#56]
@dhh1128 wrote:
> Certain checks can only be performed if we add an additional parameter, which is the proof request against which verification is being performed. Simple and important example: we ask Alice to show us her commercial driver's license. She shows us a non-commercial driver's license instead. The non-commercial driver's license will likely verify as far as its internal proof is concerned, but it doesn't match the criteria. Hackers could drive a truck through that gap.
> So, do we want to allow an extra, optional parameter which is the criteria we're supposed to be satisfying? I know that raises all kinds of problems (especially, that we don't have a standard way to express criteria). But this feels like a fairly important omission.

I agree that we need something along these lines to be passed in as an option to the API.

**Comment by peacekeeper** [comment]
We discussed this on the [05 Oct 2021 VC API Work Item call](https://w3c-ccg.github.io/meetings/2021-10-05-vchttpapi/) and felt that validation of business logic (e.g. evaluating if a VP matches a certain request) should happen outside of the API.

Also see https://github.com/w3c-ccg/vc-http-api/issues/59.

We therefore thought that this issue should be closed.

**Comment by msporny** [comment]
> We therefore thought that this issue should be closed.

Based on this comment, closing.
