### ISSUE TITLE
Align with Verifier Prerequisite Exchange specification, with Verifier Requirement Definition / Verifier Requirement Submission objects.

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/vc-api#57]
https://github.com/decentralized-identity/proof-presentation/issues/10

^ this spec is attempting to define a data model for things a verifier will accept using JSON Schema... but is transport agnostic.

If we can ensure that this is an option for this HTTP rest API, that would be great!

**Comment by peacekeeper** [comment]
We discussed this on the [05 Oct 2021 VC API Work Item call](https://w3c-ccg.github.io/meetings/2021-10-05-vchttpapi/) and felt that validation of business logic (e.g. evaluating if a VP matches a certain request) should happen outside of the API.

Also see https://github.com/w3c-ccg/vc-http-api/issues/59.

We therefore thought that this issue should be closed.

**Comment by msporny** [comment]
> We therefore thought that this issue should be closed.

Based on this comment, closing.
