### ISSUE TITLE
Need to define "verify"

### ISSUE THREAD

**Issue by dhh1128** [w3c-ccg/vc-api#59]
(moved from https://github.com/w3c-ccg/vc-issuer-http-api/issues/14)

Several things that a verifier does when evaluating a verifiable presentation are possibly intended by the verb "verify." We need to be crisp about which are in and out of scope for our API.

1. Checking the integrity of the artifact from a format and input validation perspective (correct MIME type, no magic byte sequence that makes the parsing engine blow up, the revealed "email" field actually looks like an email address, the revealed "name" field doesn't cause a buffer overrun, etc)
2. Checking digital signatures or ZK proofs in the presentation to confirm that they provide the evidence that they purport to provide.
3. Checking revocation status.
4. Checking whether a credential upon which the presentation is based was not expired for the timeframe the presentation targets.
5. Checking whether the presentation does, in fact, meet all of the criteria in the proof request. Note how this is different from item 2, in that what's proved could be less than what was requested. This includes checking whether the presentation is bound to the holder correctly (e.g., with biometrics).
6. Possibly, walking a data provenance chain in the credential and checking that it holds all the way back to the root of trust. (See [Aries RFC 0104](https://github.com/hyperledger/aries-rfcs/blob/master/concepts/0104-chained-credentials/README.md).)
6. Checking whether the presentation satisfies business requirements that were not expressible in a proof request. (For example, a verifier says they'll give some prize to the first 3 applicants who meet criteria X, Y, and Z. The proof request can express X, Y, and Z, but there's no way the verifier can demand that the holder prove they're one of the first 3 to apply. Only the verifier can test that.)

How many of these do we expect our verification API to support? And how do we distinguish between them when reporting errors?

**Comment by OR13** [comment]
We also need to include support for:

How should we expose information about "revocation list" or "expiration" verification details failing in the verifier api?

**Comment by David-Chadwick** [comment]
5,6 and 7 are validation rather than verification and therefore should be out of scope

**Comment by peacekeeper** [comment]
We discussed this on the [05 Oct 2021 VC API Work Item call](https://w3c-ccg.github.io/meetings/2021-10-05-vchttpapi/) and agreed that [verification](https://www.w3.org/TR/vc-data-model/#dfn-verify) is in scope. But we felt that validation of additional business logic (e.g. evaluating if a VP matches a certain request) should happen outside of the API.

Also see several other issues linked to this one.

It seems a PR should be created that documents this clearly in the API.

**Comment by dhh1128** [comment]
I agree with @David-Chadwick 's summary and with @peacekeeper 's call for a PR.

**Comment by msporny** [comment]
> It seems a PR should be created that documents this clearly in the API.

It looks like a PR has yet to be raised to address this issue. We need to assign someone to write that PR.

**Comment by OR13** [comment]
I don't think we should define "verify" I think we should point to the VCDM defintion.

reopen if you disagree, and intend to open a PR with a proposal.

**Comment by msporny** [comment]
> I don't think we should define "verify" I think we should point to the VCDM defintion.

I think you mean "we shouldn't define 'validate'", right? Because we define verify (checking items 2 and 3 from @dhh1128 list, but not getting into the other items because they constitute a certain sort of business logic). The expectation is that that sort of logic might be back-end configurable in the exchanges APIs, but we're not exposing any of that -- config or execution -- in the VC API).
