### ISSUE TITLE
Document check algorithms in spec, establish check registry

### ISSUE THREAD

**Issue by msporny** [w3c-ccg/vc-api#62]
We need to define all possible checks in the specification, the exact algorithm for performing each check, and establish a registry so new checks can be added without having to modify the core specification.

**Comment by peacekeeper** [comment]
We discussed this on the [05 Oct 2021 VC API Work Item call](https://w3c-ccg.github.io/meetings/2021-10-05-vchttpapi/) and felt that variability of checks is bad, i.e. there should be a fixed set of checks that each conformant implementation of the API performs, and that any additional business logic (e.g. evaluating if a VP matches a certain request) should happen outside of the API. There would therefore be no need for a registry of checks, or for options that the client could supply in the request for enabling/disabling certain checks.

Also see https://github.com/w3c-ccg/vc-http-api/issues/59.

We therefore felt that this issue could be closed.

**Comment by msporny** [comment]
> We therefore felt that this issue could be closed.

Based on this comment, closing.
