### ISSUE TITLE
Use of `created` option in verification request

### ISSUE THREAD

**Issue by clehner** [w3c-ccg/vc-api#68]
The description of the `created` option in `LinkedDataProofOptions` (for a `VerifyCredentialRequest` or `VerifyPresentationRequest`) says "The date of the proof. If omited system time will be used." ([source](https://github.com/w3c-ccg/vc-http-api/blob/master/docs/vc-http-api.yml#L157)). In the examples, the `created` option is set to a date about 20 minutes after the value of the `created` property of the proof. Does the `created` option mean that the proof's `created` date should be at or before the given date? Or is it supposed to match only the exact date?

**Comment by msporny** [comment]
This looks like a cut/paste issue from IssuerOptions.

**Comment by msporny** [comment]
Suggestion during the call was to remove `created` until we have a concrete use case.
