### ISSUE TITLE
Checks in verify options

### ISSUE THREAD

**Issue by clehner** [w3c-ccg/vc-api#74]
In the test suite (added in #65), linked data proof options contains a property `"checks": ["proof"]`.This is also used in verification results. Should `checks` be added to `LinkedDataProofOptions` in the spec? Related: #62

**Comment by OR13** [comment]
yes, imo this data model is terrible... here the caller should be asking for a specific set of checks to be run, including:

- predating
- postdating
- revocation
- expiration
- signature / proof
- schema validation

**Comment by OR13** [comment]
Proposed JSON response for various checks:

```
{
      "valid": true,
      "validations": [
        {
          "valid": true,
          "title": "Signature",
          "description": "did:key:z6MkfMDGAbnhGxB9DCHeuhtFjCpfcDpfCjXTZWuvunCXec4P#z6MkfMDGAbnhGxB9DCHeuhtFjCpfcDpfCjXTZWuvunCXec4P"
        },
        {
          "valid": true,
          "title": "Activation",
          "description": "This credential activated 9 months ago"
        },
        {
          "valid": true,
          "title": "Expiration",
          "description": "This credential expires in 8 years"
        }
      ]
    }

```

**Comment by peacekeeper** [comment]
+1 to supporting details about each individual validation/check. I think each entry in the list should also optionally have its own `error` (or similar) field to indicate why it failed.

**Comment by David-Chadwick** [comment]
Putting myself in the position of a service provider, if I ask the Verifier to verify the VP I have just received, I would want full verification to take place by default, including the embedded VCs. I would expect any verifier that ignores the validity dates to be severely deficient. I don't want a reply that tells me all the checks that have been passed. I want one Yes that tells me all tests have been passed. Conversely, if the verification fails, then I might like errors that tell me which bits failed, such as VC has expired etc. So it seems  like the API is back to front if it is passing all the positive checks but not passing all the failed ones.

**Comment by David-Chadwick** [comment]
> here the caller should be asking for a specific set of checks to be run, including:

I think this is the wrong approach. Why  would a caller only want partial verification to take place? The default must surely be to check everything

**Comment by OR13** [comment]
@David-Chadwick is your counter proposal to infer checks from the proof type and credential structure?

- credentialSchema - check if present
- credentialStatus - check if present
- proof - check if present

Sound better?

**Comment by OR13** [comment]
here we have this function: https://github.com/transmute-industries/vc.js/blob/master/packages/vc.js/src/vc-ld/validateCredential.spec.ts

**Comment by kimdhamilton** [comment]
May I interest you folks in some human-facing documentation? https://github.com/w3c-ccg/vc-http-api/pull/134

**Comment by msporny** [comment]
This seems to have stalled, what's the next step here?

**Comment by OR13** [comment]
We removed "checks", so this should be closed... we only return a "boolean" status for now, or errors.
