### ISSUE TITLE
Publish test suite under w3c-ccg

### ISSUE THREAD

**Issue by tplooker** [w3c-ccg/vc-api#79]
Following the pattern outlined in this [PR](https://github.com/w3c-ccg/universal-wallet-interop-spec/pull/44) the test suite in this repo should be re-scoped un the w3c-ccg npmjs org once created. See [here](https://github.com/w3c-ccg/universal-wallet-interop-spec/pull/44#issuecomment-725461987) for more context.

ping @w3c-ccg/chairs

**Comment by wyc** [comment]
Thanks @tplooker! We have squatted https://www.npmjs.com/org/w3c-ccg

I will add an agenda item to discuss with other chairs tomorrow how we'd like to handle the governance of this, with the ultimate goal towards community governance through something like the [Infrastructure TF](https://github.com/w3c-ccg/community/issues/168).

**Comment by OR13** [comment]
any update on this? It seems like a lot of work for the ccg... as a vendor who likes being able to publish changes easily... I am worried handy control to the ccg will slow things down.... even more.

**Comment by vsnt** [comment]
Thanks for the bump @OR13. I'll get this on our agenda or we can bring it up at the next call.

**Comment by msporny** [comment]
We discussed this on the 2021-11-16. The group felt that it's fine to hold the w3c-ccg name on npm.org, but the VC API group does not plan to publish any NPM packages in the foreseeable future to npm.org.

Next step is for the W3C CCG Chairs to message this more broadly and call for consensus among the broader CCG.
