### ISSUE TITLE
Plugfest March 2021 Feature freeze date

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/vc-api#93]
There are 4 code owners: https://github.com/w3c-ccg/vc-http-api/blob/master/CODEOWNERS

 @peacekeeper @msporny @mavarley @OR13 @mkhraisha
 
We are responsible for making sure the issues tagged with plugfest are closed before feature freeze, and that we decide to feature freeze at a specific version.

I am proposing we cut a tagged verison of the API on Feb 16.

Anything that fails to get implemented by then is not in scope for interop.

Do the other code owners agree?

**Comment by msporny** [comment]
> Anything that fails to get implemented by then is not in scope for interop.

As long as everything that happens between now and then is optional wrt. implementing for the plugfest, that's probably ok?

To be clear -- Digital Bazaar is feature complete for Phase II wrt. the VC HTTP API, we don' t need any new features to meet our assigned use case. We may choose to implement some of these new APIs, we may not. We are supportive of the other companies that need new features and will do our best to review the new features such that we would be on board with implementing them in time.

We need to run this whole plugfest thing differently next time... with feature freeze a solid 2-3 months before the plug fest (out of a 9 month contract). Weekly interop meetings should start one month after contract award.

**Comment by OR13** [comment]
> To be clear -- Digital Bazaar is feature complete for Phase II wrt. the VC HTTP API, we don' t need any new features to meet our assigned use case.

Sounds like you:

1. can't support any breaking changes
2. only intend to pass the tests you passed at the end of phase 1

I think we probably need to establish a clear way for folks to show that you still pass the old tests, and at the same time, allow for new folks to pass the newer tests, which might make use of breaking api changes or new features.

@tplooker can you see clear way to distinguish between "2020" and "2021" conformance tests?

I think I can see how this would be possible, but clearly there are vendors who don't intend to implement any of the 2021 features, we want them to still be able to pass the 2020 tests.

**Comment by mkhraisha** [comment]
> Do the other code owners agree?
yes absolutely do

**Comment by peacekeeper** [comment]
> Do the other code owners agree?

The date Feb 16 sounds good to me, however the process of how issues get tagged plugfest-march-2021 has been a bit unclear. Can anyone create/tag issues they would like to be in scope for feature freeze?

**Comment by mavarley** [comment]
> Do the other code owners agree?
Agree - and agree we need to make sure the 2020 plugfest version stays intact. 

There are other 'plugfests' that are happening outside DHS/SVIP initiative - at least one with a Canadian group under Treasury Board's UCVDCC initiative - they will need the 2020 versions of the tests to remain stable. (The mentioned initiative has a similar timeline for testing).

**Comment by OR13** [comment]
> Can anyone create/tag issues they would like to be in scope for feature freeze?

yes, but adding that tag is committing to adding support for the issue.

> There are other 'plugfests' that are happening outside DHS/SVIP initiative - at least one with a Canadian group under Treasury Board's UCVDCC initiative - they will need the 2020 versions of the tests to remain stable. (The mentioned initiative has a similar timeline for testing).

yes, the idea is to communicate clearly to everyone that `plugfest-march-2021` is UNSTABLE.... and will be frozen on Feb 16.

Until then, we can make changes to it : )

**Comment by mprorock** [comment]
@OR13 should PRs up until this point be issued against main, or against a specific branch?

**Comment by mprorock** [comment]
Code owners: @peacekeeper @msporny @mavarley @OR13 @mkhraisha

What about the notion of a Code Freeze, but a one week lag for a final freeze to add docs that may be updated or added after the code itself is frozen?

This kind of time period is reasonable, and allows us to add clarifying comments without changing and data structures or API behaviors to ensure that the code is well tested against, etc.

In this case, that would mean that the YAML (outside of comment, description, and example tags) would freeze, along with the test cases, but READMEs, code comments and docs, and the above mentioned YAML tags could be cleaned up after the code is actually in place with all merges in.

The risk is, that otherwise code changes go in and are merged, and the docs do not clearly explain those changes or the implications of those final changes, or worse yet, are in conflict with the code.

**Comment by OR13** [comment]
We should treat master/main as unstable and try and get all PRs merged into it before Feb 16.... on Feb 16 master/main should be cut as a tagged release `plugfest-march-2021` and archived.

**Comment by mprorock** [comment]
@OR13 this makes sense for the API spec itself, possibly even for the test specs in #94, but feels arbitrary.  what about documentation related to the test suite.  that pr just went in 2 days ago and I have opened #105 to start to add some docs, but this (the testing especially) is literally unapproachable by a 3rd party developer or audience in its current state

**Comment by msporny** [comment]
Overtaken by events, it is not 2022. No longer relevant. Closing.

**Comment by TallTed** [comment]
> Overtaken by events, it is not 2022. No longer relevant. Closing.

`s/not 2022/now 2022/`

**Comment by msporny** [comment]
> s/not 2022/now 2022/

Thanks @TallTed, made the change in the original comment so folks would be less confused by the closure of this issue. :)
